Repository FuelLabs/fuel-ui, pull requests merged in 2022-05, with the labels that each got.

#10 Add README with instructions to install
  README.md
Labels: documentation

#24 fix(react): missing imports
  design-system/react/src/components/index.tsx
Labels: bug

#25 refac: change workspaces structure to support apps with contracts
  README.md
  apps/example/frontend/.gitignore
  apps/example/frontend/README.md
  apps/example/frontend/index.html
  apps/example/frontend/jest.config.ts
  apps/example/frontend/package.json
  apps/example/frontend/public/favicon.svg
  apps/example/frontend/src/App.tsx
  apps/example/frontend/src/main.tsx
  apps/example/frontend/src/routes.tsx
  apps/example/frontend/src/systems/Core/components/Layout.tsx
  apps/example/frontend/src/systems/Core/components/Link.tsx
  apps/example/frontend/src/systems/Core/components/TopNav.tsx
  apps/example/frontend/src/systems/Core/index.tsx
  apps/example/frontend/src/systems/Core/pages/Home.tsx
  apps/example/frontend/src/systems/Core/pages/index.tsx
  apps/example/frontend/src/systems/Core/routes.tsx
  apps/example/frontend/src/systems/Token/index.tsx
  apps/example/frontend/src/systems/Token/pages/Token.tsx
  apps/example/frontend/src/systems/Token/pages/Tokens.tsx
  apps/example/frontend/src/systems/Token/pages/index.tsx
  apps/example/frontend/src/systems/Token/routes.tsx
  apps/example/frontend/src/vite-env.d.ts
  apps/example/frontend/tsconfig.json
  apps/example/frontend/tsconfig.node.json
  apps/example/frontend/vite.config.ts
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: enhancement, architecture

#36 refactor: setup escrow with the appropriate project structure
  apps/escrow/frontend/.gitignore
  apps/escrow/frontend/README.md
  apps/escrow/frontend/index.html
  apps/escrow/frontend/jest.config.ts
  apps/escrow/frontend/package.json
  apps/escrow/frontend/public/favicon.svg
  apps/escrow/frontend/src/App.tsx
  apps/escrow/frontend/src/config.ts
  apps/escrow/frontend/src/main.tsx
  apps/escrow/frontend/src/routes.tsx
  apps/escrow/frontend/src/systems/Core/components/Layout.tsx
  apps/escrow/frontend/src/systems/Core/components/Link.tsx
  apps/escrow/frontend/src/systems/Core/components/RequireWallet.tsx
  apps/escrow/frontend/src/systems/Core/components/TopNav.tsx
  apps/escrow/frontend/src/systems/Core/context/AppContext.tsx
  apps/escrow/frontend/src/systems/Core/index.tsx
  apps/escrow/frontend/src/systems/Core/pages/CreateWallet.tsx
  apps/escrow/frontend/src/systems/Core/pages/Escrow.tsx
  apps/escrow/frontend/src/systems/Core/pages/index.tsx
  apps/escrow/frontend/src/systems/Core/routes.tsx
  apps/escrow/frontend/src/systems/Core/types/pages.ts
  apps/escrow/frontend/src/vite-env.d.ts
  apps/escrow/frontend/tsconfig.json
  apps/escrow/frontend/tsconfig.node.json
  apps/escrow/frontend/vite.config.ts
  pnpm-lock.yaml
Labels: enhancement
