Repository FuelLabs/fuel-ui, pull requests merged in 2023-05, with the labels that each got.

#223 feat: add asset dropdown to amount input
  design-system/react/package.json
  design-system/react/public/assets/eth.svg
  design-system/react/src/components/InputAmount/InputAmount.stories.tsx
  design-system/react/src/components/InputAmount/InputAmount.tsx
  design-system/react/src/components/InputAmount/InputAmountLoader.tsx
  design-system/react/src/components/Tooltip/Tooltip.tsx
  pnpm-lock.yaml
Labels: enhancement, @ds:form

#251 feat: use tabler icons instead of phosphor icons
  .changeset/gentle-snakes-pump.md
  common/config/package.json
  common/test-utils/package.json
  design-system/react/README.md
  design-system/react/package.json
  design-system/react/src/components/Accordion/AccordionTrigger.tsx
  design-system/react/src/components/Alert/Alert.tsx
  design-system/react/src/components/ButtonLink/ButtonLink.tsx
  design-system/react/src/components/CardList/CardList.stories.tsx
  design-system/react/src/components/Copyable/Copyable.stories.tsx
  design-system/react/src/components/Copyable/Copyable.tsx
  design-system/react/src/components/Dialog/DialogClose.tsx
  design-system/react/src/components/Drawer/DrawerClose.tsx
  design-system/react/src/components/Dropdown/Dropdown.stories.tsx
  design-system/react/src/components/Dropdown/Dropdown.test.tsx
  design-system/react/src/components/Dropdown/DropdownTrigger.tsx
  design-system/react/src/components/Form/Form.stories.tsx
  design-system/react/src/components/HelperIcon/HelperIcon.tsx
  design-system/react/src/components/Icon/Icon.stories.tsx
  design-system/react/src/components/Icon/Icon.tsx
  design-system/react/src/components/Icon/defs.ts
  design-system/react/src/components/Input/Input.stories.tsx
  design-system/react/src/components/InputAmount/InputAmount.tsx
  design-system/react/src/components/Link/Link.tsx
  design-system/react/src/components/Menu/Menu.stories.tsx
  design-system/react/src/components/Pagination/PaginationNav.tsx
  design-system/react/src/components/PasswordStrength/PasswordStrength.tsx
  design-system/react/src/components/Popover/Popover.tsx
  design-system/react/src/components/Tabs/Tabs.stories.tsx
  design-system/react/src/components/Tag/TagCloseButton.tsx
  design-system/react/src/components/ThemeProvider/ThemeProvider.tsx
  design-system/react/src/components/Toast/Toast.tsx
  examples/custom-theme/package.json
  package.json
  pnpm-lock.yaml
Labels: breaking-change

#255 fix: amountInput for 18 units
  design-system/react/src/components/InputAmount/InputAmount.stories.tsx
  design-system/react/src/components/InputAmount/InputAmount.test.tsx
  design-system/react/src/components/InputAmount/InputAmount.tsx
  design-system/react/src/components/InputAmount/utils.tsx
Labels: bug
